/**
 * This file was auto-generated by generate-custom-requests script.
 * Do not edit manually.
 */
import { z } from "zod";

export const generatedCustomRequestsRegistry = {
	"0j7f9fuzuo7": {
		key: "0j7f9fuzuo7",
		name: "0j7f9fuzuo7",
		collection: "t_qualirun_info_adicionais",
		options: {
			method: "POST",
			url: "https://atplus-rh-n8n-rh.tvs9na.easypanel.host/webhook/9ceda127-997b-49df-8037-f50db4a55e42",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"23btjo9ohrr": {
		key: "23btjo9ohrr",
		name: "23btjo9ohrr",
		collection: "cliente_contrato",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/5d9eccc3-7091-47f9-bcae-75ea5292b7fd",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"32fmnujkpaq": {
		key: "32fmnujkpaq",
		name: "32fmnujkpaq",
		collection: "radusuarios",
		options: { method: "GET", url: "https://n8n.atplus.cloud/webhook/aegis" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"37yaihkravc": {
		key: "37yaihkravc",
		name: "37yaihkravc",
		collection: "cliente_contrato",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/0860593c-859a-4427-9e7e-437b19bed46b",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"3jd8i67j41e": {
		key: "3jd8i67j41e",
		name: "3jd8i67j41e",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/37cbdc46-4512-43e0-a89d-21e0d45de960",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"4pqt2osnjwb": {
		key: "4pqt2osnjwb",
		name: "4pqt2osnjwb",
		collection: "radusuarios",
		options: { method: "GET", url: "https://n8n.atplus.cloud/webhook/aegis" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"5kd0wmsvdo2": {
		key: "5kd0wmsvdo2",
		name: "5kd0wmsvdo2",
		collection: "t_comentarios_demandas",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_demandas:update?filterByTk=73",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"5t5w4obvlfl": {
		key: "5t5w4obvlfl",
		name: "5t5w4obvlfl",
		collection: "cliente_contrato",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/5f130ffe-2cf6-4f42-8f05-ef8aed602644",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"6ke3hsmki23": {
		key: "6ke3hsmki23",
		name: "6ke3hsmki23",
		collection: "cliente_contrato",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_negociacoes:create",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"73roqp9a2rc": {
		key: "73roqp9a2rc",
		name: "73roqp9a2rc",
		collection: "radusuarios",
		options: { method: "GET", url: "https://n8n.atplus.cloud/webhook/aegis" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"78d5kny2gwn": {
		key: "78d5kny2gwn",
		name: "78d5kny2gwn",
		collection: "cliente_contrato",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/5f130ffe-2cf6-4f42-8f05-ef8aed602644",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"7bsfl4wnz5m": {
		key: "7bsfl4wnz5m",
		name: "7bsfl4wnz5m",
		collection: "cliente_contrato",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook-test/demandas",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"7fh1n04ztsu": {
		key: "7fh1n04ztsu",
		name: "7fh1n04ztsu",
		collection: "t_zapsign",
		options: {
			method: "GET",
			url: "https://api.zapsign.com.br/api/v1/info-plan/",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"7u4q8xjflzh": {
		key: "7u4q8xjflzh",
		name: "7u4q8xjflzh",
		collection: "radusuarios",
		options: { method: "GET", url: "https://n8n.atplus.cloud/webhook/aegis" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"81p695ox20f": {
		key: "81p695ox20f",
		name: "81p695ox20f",
		collection: "f_funcionarios",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/8dbc006d-f3b1-42a5-a715-7c7025655146",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"8e9nkpsadjm": {
		key: "8e9nkpsadjm",
		name: "8e9nkpsadjm",
		collection: "t_negociacoes",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/bec8f4d4-b0ad-4e3a-a42e-53e99674fe8d",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"93xtl7ut9gz": {
		key: "93xtl7ut9gz",
		name: "93xtl7ut9gz",
		collection: "su_oss_chamado",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/acoesos",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	"9eedntq884w": {
		key: "9eedntq884w",
		name: "9eedntq884w",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_negociacoes_itens:create",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	b186501hwq6: {
		key: "b186501hwq6",
		name: "b186501hwq6",
		collection: "t_atendimentos_ixc",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/aegis-crm",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	b4xb4urp530: {
		key: "b4xb4urp530",
		name: "b4xb4urp530",
		collection: "radusuarios",
		options: { method: "GET", url: "https://n8n.atplus.cloud/webhook/aegis" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	bq0cb339042: {
		key: "bq0cb339042",
		name: "bq0cb339042",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/7951a79e-7efc-49ac-bd63-9ec9d9f0b225",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	cpjti4z0134: {
		key: "cpjti4z0134",
		name: "cpjti4z0134",
		collection: "radusuarios",
		options: { method: "GET", url: "https://n8n.atplus.cloud/webhook/aegis" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	d349ih50xzh: {
		key: "d349ih50xzh",
		name: "d349ih50xzh",
		collection: "t_demandas",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_demandas:update?filterByTk={{currentRecord.id}}",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	d6ksnfld3et: {
		key: "d6ksnfld3et",
		name: "d6ksnfld3et",
		collection: "t_pessoas",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/b43a1b28-e8e9-4aaf-86da-2289a4d5e233",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	dubcidu6jmc: {
		key: "dubcidu6jmc",
		name: "dubcidu6jmc",
		collection: "t_negociacoes",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/bec8f4d4-b0ad-4e3a-a42e-53e99674fe8d",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	f8q6gymke8a: {
		key: "f8q6gymke8a",
		name: "f8q6gymke8a",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/envia-para-assinatura",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	fiss44qjf20: {
		key: "fiss44qjf20",
		name: "fiss44qjf20",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_negociacoes:update?filterByTk={{currentRecord.id}}",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	gehbxharfjz: {
		key: "gehbxharfjz",
		name: "gehbxharfjz",
		collection: "t_atendimentos_ixc",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/aegisatendimento",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	ghcsm5m6cb8: {
		key: "ghcsm5m6cb8",
		name: "ghcsm5m6cb8",
		collection: "t_patrimonio",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/8dbc006d-f3b1-42a5-a715-7c7025655146",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	gp4mrt26bbe: {
		key: "gp4mrt26bbe",
		name: "gp4mrt26bbe",
		collection: "t_demandas",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/d86bf3fb-47da-4abc-916b-e08ebd07e231",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	h0h7rujhvvj: {
		key: "h0h7rujhvvj",
		name: "h0h7rujhvvj",
		collection: "t_pessoas",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/cb200573-5c18-4a03-bb62-69cad03a2be4",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	h32vk2yid08: {
		key: "h32vk2yid08",
		name: "h32vk2yid08",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/b2b40644-0463-4d36-8c1b-89db9ffb2880",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	h901q2xewqo: {
		key: "h901q2xewqo",
		name: "h901q2xewqo",
		collection: "su_oss_chamado",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/7578902b-c9b8-48df-a299-d21813709f13",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	il2pcooj4pr: {
		key: "il2pcooj4pr",
		name: "il2pcooj4pr",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/envia-assinatura",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	im5okkvu9dz: {
		key: "im5okkvu9dz",
		name: "im5okkvu9dz",
		collection: "vd_contratos_produtos",
		options: {
			method: "POST",
			url: "https://45.229.104.23/webservice/v1/su_ticket",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	iwdrxnxtmdq: {
		key: "iwdrxnxtmdq",
		name: "iwdrxnxtmdq",
		collection: "t_atendimentos_ixc",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/aegisatendimento",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	jhzlhxs8owo: {
		key: "jhzlhxs8owo",
		name: "jhzlhxs8owo",
		collection: "t_atendimentos_ixc",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/demandas",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	kgm9ahtf2yp: {
		key: "kgm9ahtf2yp",
		name: "kgm9ahtf2yp",
		collection: "cliente_contrato",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/0860593c-859a-4427-9e7e-437b19bed46b",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	lt9r40c3a52: {
		key: "lt9r40c3a52",
		name: "lt9r40c3a52",
		collection: "t_atendimentos_ixc",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/acoesos",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	m5pu59k8p9s: {
		key: "m5pu59k8p9s",
		name: "m5pu59k8p9s",
		collection: "fn_areceber",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/9571dab3-4e39-429e-a602-ae3619819b70",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	mp73jhvvcuj: {
		key: "mp73jhvvcuj",
		name: "mp73jhvvcuj",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_negociacoes:update?filterByTk={{currentRecord.id}}",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	mzpjc6seq2p: {
		key: "mzpjc6seq2p",
		name: "mzpjc6seq2p",
		collection: "t_atendimentos_ixc",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/aegisatendimento",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	oj5jwqjdjts: {
		key: "oj5jwqjdjts",
		name: "oj5jwqjdjts",
		collection: "radusuarios",
		options: { method: "GET", url: "https://n8n.atplus.cloud/webhook/aegis" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	q5cd310hudg: {
		key: "q5cd310hudg",
		name: "q5cd310hudg",
		collection: "t_contratos_ixc",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/cb200573-5c18-4a03-bb62-69cad03a2be4",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	qtd2du574v1: {
		key: "qtd2du574v1",
		name: "qtd2du574v1",
		collection: "cliente_contrato",
		options: {
			method: "POST",
			url: "https://{{$env.IXC_Domain}}/webservice/v1/desbloqueio_confianca",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	rc6bqjtcfik: {
		key: "rc6bqjtcfik",
		name: "rc6bqjtcfik",
		collection: "t_atendimentos_ixc",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/acoesos",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	rm9a8dyqfzr: {
		key: "rm9a8dyqfzr",
		name: "rm9a8dyqfzr",
		collection: "t_crm_troca_titularidade",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_crm_troca_titularidade:update?filterByTk={{currentRecord.id}}",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	s0vwyf6kzdl: {
		key: "s0vwyf6kzdl",
		name: "s0vwyf6kzdl",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_negociacoes:update?filterByTk={{currentRecord.id}}",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	s1hoaij5zg3: {
		key: "s1hoaij5zg3",
		name: "s1hoaij5zg3",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_negociacoes:update?filterByTk={{currentRecord.id}}",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	sjohhcwirxz: {
		key: "sjohhcwirxz",
		name: "sjohhcwirxz",
		collection: "fn_areceber",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/c97170a1-15fe-44ca-a302-f9e7b2c54b63",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	sl7o14v2qhm: {
		key: "sl7o14v2qhm",
		name: "sl7o14v2qhm",
		collection: "fn_areceber",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/68c0ddb3-6416-4093-88f3-ba7873581729.pdf",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	smabb16kusp: {
		key: "smabb16kusp",
		name: "smabb16kusp",
		collection: "t_telecom_ips_fixos",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/a24ba316-aed8-4bc2-a949-c6cb038a3fe7",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	spn119qrcv8: {
		key: "spn119qrcv8",
		name: "spn119qrcv8",
		collection: "fn_areceber",
		options: { method: "GET", url: "https://placehold.co/600x400.png" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	t3x4cxkvz4l: {
		key: "t3x4cxkvz4l",
		name: "t3x4cxkvz4l",
		collection: "vd_contratos_produtos",
		options: {
			method: "POST",
			url: "https://45.229.104.23/webservice/v1/su_ticket",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	t8csht5gpmi: {
		key: "t8csht5gpmi",
		name: "t8csht5gpmi",
		collection: "t_contratos_ixc",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/cb200573-5c18-4a03-bb62-69cad03a2be4",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	tjt1ajr1tkl: {
		key: "tjt1ajr1tkl",
		name: "tjt1ajr1tkl",
		collection: "cliente_contrato",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/segundacontratacao",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	u1t103p3ra5: {
		key: "u1t103p3ra5",
		name: "u1t103p3ra5",
		collection: "t_demandas",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook-test/demandas",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	uw77gy8qtte: {
		key: "uw77gy8qtte",
		name: "uw77gy8qtte",
		collection: "t_dados_adicionais_cliente_contrato",
		options: { method: "POST", url: "/" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	vwl8w2fpjzg: {
		key: "vwl8w2fpjzg",
		name: "vwl8w2fpjzg",
		collection: "t_demandas",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/71977efe-295b-49d5-b36b-83040a36dd33",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	wr4aj0srq5h: {
		key: "wr4aj0srq5h",
		name: "wr4aj0srq5h",
		collection: "t_trocasdetitularidade_comentarios",
		options: {
			method: "POST",
			url: "https://crm.atplus.cloud/api/t_crm_troca_titularidade:update/13",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	xk24zkcao2z: {
		key: "xk24zkcao2z",
		name: "xk24zkcao2z",
		collection: "t_negociacoes",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook/b2b40644-0463-4d36-8c1b-89db9ffb2880",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	xkmkcdnrksu: {
		key: "xkmkcdnrksu",
		name: "xkmkcdnrksu",
		collection: "t_atendimentos_ixc",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/aegisatendimento",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	ychaqev81oe: {
		key: "ychaqev81oe",
		name: "ychaqev81oe",
		collection: "t_atendimentos_ixc",
		options: {
			method: "GET",
			url: "https://n8n.atplus.cloud/webhook/demandas",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	yep1cjhq0zp: {
		key: "yep1cjhq0zp",
		name: "yep1cjhq0zp",
		collection: "f_funcionarios",
		options: {
			method: "POST",
			url: "https://atplus-rh-n8n-rh.tvs9na.easypanel.host/webhook/4edc42ad-6d41-47f6-9a2f-4b536f4e92ae",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	ygimowrypfa: {
		key: "ygimowrypfa",
		name: "ygimowrypfa",
		collection: "su_ticket",
		options: {
			method: "POST",
			url: "https://n8n.atplus.cloud/webhook-test/d86bf3fb-47da-4abc-916b-e08ebd07e231",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	ynsgglxpt3r: {
		key: "ynsgglxpt3r",
		name: "ynsgglxpt3r",
		collection: "radusuarios",
		options: { method: "GET", url: "https://n8n.atplus.cloud/webhook/aegis" },
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},

	ysw34sgdr52: {
		key: "ysw34sgdr52",
		name: "ysw34sgdr52",
		collection: "t_qualirun_processos",
		options: {
			method: "PUT",
			url: "https://utxejnodralnuthfwzoo.supabase.co/functions/v1/public-api/execution-orders/{{$nSelectedRecord.f_id_externo}}",
		},
		payloadSchema: z.any(),
		_hasEnhancedSchema: false,
	},
} as const;

export const collectionToRequestKeys = {
	cliente_contrato: [
		"23btjo9ohrr",
		"37yaihkravc",
		"5t5w4obvlfl",
		"6ke3hsmki23",
		"78d5kny2gwn",
		"7bsfl4wnz5m",
		"kgm9ahtf2yp",
		"qtd2du574v1",
		"tjt1ajr1tkl",
	],
	f_funcionarios: ["81p695ox20f", "yep1cjhq0zp"],
	fn_areceber: ["m5pu59k8p9s", "sjohhcwirxz", "sl7o14v2qhm", "spn119qrcv8"],
	radusuarios: [
		"32fmnujkpaq",
		"4pqt2osnjwb",
		"73roqp9a2rc",
		"7u4q8xjflzh",
		"b4xb4urp530",
		"cpjti4z0134",
		"oj5jwqjdjts",
		"ynsgglxpt3r",
	],
	su_oss_chamado: ["93xtl7ut9gz", "h901q2xewqo"],
	su_ticket: ["ygimowrypfa"],
	t_atendimentos_ixc: [
		"b186501hwq6",
		"gehbxharfjz",
		"iwdrxnxtmdq",
		"jhzlhxs8owo",
		"lt9r40c3a52",
		"mzpjc6seq2p",
		"rc6bqjtcfik",
		"xkmkcdnrksu",
		"ychaqev81oe",
	],
	t_comentarios_demandas: ["5kd0wmsvdo2"],
	t_contratos_ixc: ["q5cd310hudg", "t8csht5gpmi"],
	t_crm_troca_titularidade: ["rm9a8dyqfzr"],
	t_dados_adicionais_cliente_contrato: ["uw77gy8qtte"],
	t_demandas: ["d349ih50xzh", "gp4mrt26bbe", "u1t103p3ra5", "vwl8w2fpjzg"],
	t_negociacoes: [
		"3jd8i67j41e",
		"8e9nkpsadjm",
		"9eedntq884w",
		"bq0cb339042",
		"dubcidu6jmc",
		"f8q6gymke8a",
		"fiss44qjf20",
		"h32vk2yid08",
		"il2pcooj4pr",
		"mp73jhvvcuj",
		"s0vwyf6kzdl",
		"s1hoaij5zg3",
		"xk24zkcao2z",
	],
	t_patrimonio: ["ghcsm5m6cb8"],
	t_pessoas: ["d6ksnfld3et", "h0h7rujhvvj"],
	t_qualirun_info_adicionais: ["0j7f9fuzuo7"],
	t_qualirun_processos: ["ysw34sgdr52"],
	t_telecom_ips_fixos: ["smabb16kusp"],
	t_trocasdetitularidade_comentarios: ["wr4aj0srq5h"],
	t_zapsign: ["7fh1n04ztsu"],
	vd_contratos_produtos: ["im5okkvu9dz", "t3x4cxkvz4l"],
} as const;
