import { execFile } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { GeneratedRegistryEntry } from "@scripts/generate-custom-requests/src/@types/generated-registry";
import { logInfo, logVerbose } from "@scripts/generate-types/src/utils/logger";

function escapeString(str: string): string {
	return str
		.replace(/\\/g, "\\\\")
		.replace(/"/g, '\\"')
		.replace(/\n/g, "\\n")
		.replace(/\r/g, "\\r")
		.replace(/\t/g, "\\t");
}

function buildCollectionToRequestKeys(
	entries: GeneratedRegistryEntry[],
): string {
	const collectionMap: Record<string, string[]> = {};

	for (const entry of entries) {
		if (!collectionMap[entry.collection]) {
			collectionMap[entry.collection] = [];
		}
		collectionMap[entry.collection].push(entry.key);
	}

	const lines = Object.entries(collectionMap)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(
			([collection, keys]) =>
				`  "${collection}": [${keys
					.sort()
					.map((k) => `"${k}"`)
					.join(", ")}],`,
		)
		.join("\n");

	return `export const collectionToRequestKeys = {\n${lines}\n} as const;`;
}

function buildRegistryContent(
	entries: GeneratedRegistryEntry[],
	splitRequests: string[],
): string {
	const sorted = [...entries].sort((a, b) => a.key.localeCompare(b.key));

	const entryLines = sorted
		.map((entry) => {
			const escapedName = escapeString(entry.name);
			const hasEnhanced = splitRequests.includes(entry.key);
			return `  "${entry.key}": {
    key: "${entry.key}",
    name: "${escapedName}",
    collection: "${entry.collection}",
    options: { method: "${entry.method}", url: "${entry.url}" },
    payloadSchema: z.any(),
    _hasEnhancedSchema: ${hasEnhanced},
  },`;
		})
		.join("\n\n");

	const collectionMapping = buildCollectionToRequestKeys(entries);

	return `/**
 * This file was auto-generated by generate-custom-requests script.
 * Do not edit manually.
 */
import { z } from "zod";

export const generatedCustomRequestsRegistry = {
 ${entryLines}
} as const;

${collectionMapping}
`;
}

function runBiomeFix(filePath: string): Promise<void> {
	return new Promise((resolve) => {
		execFile(
			"biome",
			["check", "--write", filePath],
			(error, stdout, stderr) => {
				if (stdout) logVerbose(stdout);
				if (stderr) logVerbose(stderr);
				if (error) {
					logInfo(
						`⚠️  Biome retornou erro (pode ser apenas warnings): ${error.message}`,
					);
				} else {
					logInfo("✅ Biome aplicado com sucesso no registry gerado");
				}
				resolve();
			},
		);
	});
}

export async function writeGeneratedRegistry(
	entries: GeneratedRegistryEntry[],
	outputDir: string,
	splitRequests: string[] = [],
): Promise<void> {
	const content = buildRegistryContent(entries, splitRequests);
	const outputPath = resolve(outputDir, "generated-registry.ts");

	logInfo(`📝 Gerando registry em: ${outputPath}`);

	writeFileSync(outputPath, content, "utf-8");

	logInfo("✅ Arquivo escrito com sucesso");

	await runBiomeFix(outputPath);
}
