import { execFile } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { GeneratedRegistryEntry } from "@scripts/generate-custom-requests/src/@types/generated-registry";
import type { SplitRequestsMap } from "@scripts/generate-custom-requests/src/@types/script-config";
import { logInfo, logVerbose } from "@scripts/shared/utils/logger";
import {
	escapeString,
	serializePayloadData,
} from "@scripts/shared/utils/strings";

function toSafeIdentifier(value: string): string {
	return value.replace(/[^a-zA-Z0-9_]/g, "_");
}

function toSafePathSegment(value: string): string {
	return value.replace(/[^a-zA-Z0-9_-]/g, "-");
}

function buildCollectionToRequestKeys(
	entries: GeneratedRegistryEntry[],
): string {
	const collectionMap: Record<string, string[]> = {};

	for (const entry of entries) {
		if (!collectionMap[entry.collection]) {
			collectionMap[entry.collection] = [];
		}
		collectionMap[entry.collection].push(entry.key);
	}

	const lines = Object.entries(collectionMap)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(
			([collection, keys]) =>
				`  "${collection}": [${keys
					.sort()
					.map((k) => `"${k}"`)
					.join(", ")}],`,
		)
		.join("\n");

	return `export const collectionToRequestKeys = {\n${lines}\n} as const;`;
}

function buildRegistryContent(
	entries: GeneratedRegistryEntry[],
	splitRequests: SplitRequestsMap,
): string {
	const sorted = [...entries].sort((a, b) => a.key.localeCompare(b.key));
	const splitRequestsSet = new Set(Object.keys(splitRequests));
	const inlineEntries = sorted.filter(
		(entry) => !splitRequestsSet.has(entry.key),
	);

	const splitImports = sorted
		.filter((entry) => splitRequestsSet.has(entry.key))
		.map((entry) => {
			const splitFileName = splitRequests[entry.key];
			const dataSourceDir = toSafePathSegment(entry.dataSourceKey);
			const collectionDir = toSafePathSegment(entry.collection);
			const alias = `split_${toSafeIdentifier(`${dataSourceDir}_${collectionDir}_${splitFileName}`)}`;
			return `import { requestEntry as ${alias}RequestEntry } from "./split/${dataSourceDir}/${collectionDir}/${splitFileName}";`;
		})
		.join("\n");

	const entryLines = sorted
		.map((entry) => {
			const hasEnhanced = splitRequestsSet.has(entry.key);
			if (hasEnhanced) {
				const splitFileName = splitRequests[entry.key];
				const dataSourceDir = toSafePathSegment(entry.dataSourceKey);
				const collectionDir = toSafePathSegment(entry.collection);
				const alias = `split_${toSafeIdentifier(`${dataSourceDir}_${collectionDir}_${splitFileName}`)}`;
				return `  "${entry.key}": ${alias}RequestEntry,`;
			}
			const escapedName = escapeString(entry.name);
			const payloadDataStr = serializePayloadData(entry.payloadData);

			return `  "${entry.key}": {
    key: "${entry.key}",
    name: "${escapedName}",
    collection: "${entry.collection}",
    dataSourceKey: "${entry.dataSourceKey}",
    method: "${entry.method}",
    url: "${entry.url}",
    payloadSchema: ${entry.payloadSchema},
    payloadData: ${payloadDataStr},
  },`;
		})
		.join("\n\n");

	const collectionMapping = buildCollectionToRequestKeys(entries);

	return `/**
 * This file was auto-generated by generate-custom-requests script.
 * Do not edit manually.
 */
${inlineEntries.length > 0 ? 'import { z } from "zod";\n' : ""}${splitImports ? `${splitImports}\n` : ""}

export const generatedCustomRequestsRegistry = {
 ${entryLines}
} as const;

export const customRequestsRegistry = generatedCustomRequestsRegistry;

export type CustomRequestRegistryKey = keyof typeof customRequestsRegistry;

${collectionMapping}
`;
}

function runBiomeFix(filePath: string): Promise<void> {
	return new Promise((resolve) => {
		execFile(
			"biome",
			["check", "--write", filePath],
			(error, stdout, stderr) => {
				if (stdout) logVerbose(stdout);
				if (stderr) logVerbose(stderr);
				if (error) {
					logInfo(
						`⚠️  Biome retornou erro (pode ser apenas warnings): ${error.message}`,
					);
				} else {
					logInfo("✅ Biome aplicado com sucesso no registry gerado");
				}
				resolve();
			},
		);
	});
}

export async function writeGeneratedRegistry(
	entries: GeneratedRegistryEntry[],
	outputDir: string,
	splitRequests: SplitRequestsMap = {},
): Promise<void> {
	const content = buildRegistryContent(entries, splitRequests);
	const outputPath = resolve(outputDir, "generated-registry.ts");

	logInfo(`📝 Gerando registry em: ${outputPath}`);

	writeFileSync(outputPath, content, "utf-8");

	logInfo("✅ Arquivo escrito com sucesso");

	await runBiomeFix(outputPath);
}
