import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { GeneratedRegistryEntry } from "@scripts/generate-custom-requests/src/@types/generated-registry";
import type { SplitRequestsMap } from "@scripts/generate-custom-requests/src/@types/script-config";
import { logger } from "@scripts/shared/utils/logger";
import {
	escapeString,
	serializePayloadData,
} from "@scripts/shared/utils/strings";

function buildSplitFileContent(entry: GeneratedRegistryEntry): string {
	const escapedKey = escapeString(entry.key);
	const escapedName = escapeString(entry.name);
	const escapedCollection = escapeString(entry.collection);
	const escapedMethod = escapeString(entry.method);
	const escapedUrl = escapeString(entry.url);
	const payloadDataStr = serializePayloadData(entry.payloadData);

	return `import { z } from "zod";

/**
 * Custom request: ${escapedName}
 * Collection: ${entry.collection}
 * Method: ${entry.method}
 * URL: ${entry.url}
 *
 * This file was auto-generated by generate-custom-requests script.
 * Do not edit manually — this file is preserved on regeneration.
 */
export const payloadSchema = ${entry.payloadSchema};

export const payloadData = ${payloadDataStr};

export const requestEntry = {
	key: "${escapedKey}",
	name: "${escapedName}",
	collection: "${escapedCollection}",
	method: "${escapedMethod}",
	url: "${escapedUrl}",
	payloadSchema,
	payloadData,
	_hasEnhancedSchema: true,
} as const;
`;
}

export function writeSplitFile(
	entry: GeneratedRegistryEntry,
	outputDir: string,
): void {
	const splitDir = resolve(outputDir, "split");
	const filePath = join(splitDir, `${entry.key}.ts`);

	const content = buildSplitFileContent(entry);
	writeFileSync(filePath, content, "utf-8");
	logger.debug(`Split file atualizado: ${entry.key}`);
}

export function writeAllSplitFiles(
	entries: GeneratedRegistryEntry[],
	splitRequests: SplitRequestsMap,
	outputDir: string,
): void {
	const splitRequestKeys = new Set(Object.keys(splitRequests));
	const splitEntries = entries.filter((entry) =>
		splitRequestKeys.has(entry.key),
	);

	for (const entry of splitEntries) {
		writeSplitFile(entry, outputDir);
	}

	logger.info(`${splitEntries.length} split files atualizados`);
}
