import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { GeneratedRegistryEntry } from "@scripts/generate-custom-requests/src/@types/generated-registry";
import type { SplitRequestsMap } from "@scripts/generate-custom-requests/src/@types/script-config";
import { logger } from "@scripts/shared/utils/logger";
import {
	escapeString,
	serializePayloadData,
} from "@scripts/shared/utils/strings";

function buildSplitFileContent(
	entry: GeneratedRegistryEntry,
	displayName: string,
): string {
	const escapedKey = escapeString(entry.key);
	const escapedName = escapeString(displayName);
	const escapedCollection = escapeString(entry.collection);
	const escapedMethod = escapeString(entry.method);
	const escapedUrl = escapeString(entry.url);
	const payloadDataStr = serializePayloadData(entry.payloadData);

	return `import { z } from "zod";

/**
 * Custom request: ${escapedName}
 * Collection: ${entry.collection}
 * Method: ${entry.method}
 * URL: ${entry.url}
 *
 * This file was auto-generated by generate-custom-requests script.
 * Do not edit manually — this file is preserved on regeneration.
 */
export const payloadSchema = ${entry.payloadSchema};

export const payloadData = ${payloadDataStr};

export const requestEntry = {
	key: "${escapedKey}",
	name: "${escapedName}",
	collection: "${escapedCollection}",
	method: "${escapedMethod}",
	url: "${escapedUrl}",
	payloadSchema,
	payloadData,
} as const;
`;
}

function toSafePathSegment(value: string): string {
	return value.replace(/[^a-zA-Z0-9_-]/g, "-");
}

export function writeSplitFile(
	entry: GeneratedRegistryEntry,
	splitFileName: string,
	outputDir: string,
): void {
	const splitDir = resolve(outputDir, "split");
	const collectionDir = toSafePathSegment(entry.collection);
	const splitCollectionDir = join(splitDir, collectionDir);
	const filePath = join(splitCollectionDir, `${splitFileName}.ts`);

	mkdirSync(splitCollectionDir, { recursive: true });

	const content = buildSplitFileContent(entry, splitFileName);
	writeFileSync(filePath, content, "utf-8");
	logger.debug(`Split file atualizado: ${splitFileName}`);

	const legacyKeyFilePath = join(splitDir, `${entry.key}.ts`);
	if (
		splitFileName !== entry.key &&
		existsSync(legacyKeyFilePath) &&
		legacyKeyFilePath !== filePath
	) {
		unlinkSync(legacyKeyFilePath);
		logger.debug(`Split file legado removido: ${entry.key}.ts`);
	}

	const legacyNamedFilePath = join(splitDir, `${splitFileName}.ts`);
	if (existsSync(legacyNamedFilePath) && legacyNamedFilePath !== filePath) {
		unlinkSync(legacyNamedFilePath);
		logger.debug(`Split file legado removido: ${splitFileName}.ts`);
	}
}

export function writeAllSplitFiles(
	entries: GeneratedRegistryEntry[],
	splitRequests: SplitRequestsMap,
	outputDir: string,
): void {
	const splitRequestKeys = new Set(Object.keys(splitRequests));
	const splitEntries = entries.filter((entry) =>
		splitRequestKeys.has(entry.key),
	);

	for (const entry of splitEntries) {
		const splitFileName = splitRequests[entry.key];
		writeSplitFile(entry, splitFileName, outputDir);
	}

	logger.info(`${splitEntries.length} split files atualizados`);
}
