import { CIDADE_RELATIONS } from "./cidade";
import { CLIENTE_RELATIONS } from "./cliente";
import { CLIENTE_CONTRATO_RELATIONS } from "./cliente-contrato";
import {
	FN_ARECEBER_RELATIONS,
	LINHA_MVNO_RELATIONS,
	SU_TICKET_RELATIONS,
	VD_CONTRATOS_PRODUTOS_RELATIONS,
} from "./financeiro";

export const IXC_RELATIONS_MAP = {
	...CIDADE_RELATIONS,
	...CLIENTE_RELATIONS,
	...CLIENTE_CONTRATO_RELATIONS,
	...FN_ARECEBER_RELATIONS,
	...LINHA_MVNO_RELATIONS,
	...VD_CONTRATOS_PRODUTOS_RELATIONS,
	...SU_TICKET_RELATIONS,
};
