import { execFile } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Logger } from "@scripts/generators/src/lib/logger";
import { logger as defaultRuntimeLogger } from "@scripts/generators/src/lib/logger";
import type { GeneratedRegistryEntry } from "../../../@types/generated-registry";
import type { RequestsMap } from "../../../@types/script-config";
import { serializeEntryFields } from "./entry-serialization";
import { resolveSplitPathInfo } from "./split-paths";

function toSafeIdentifier(value: string): string {
	return value.replace(/[^a-zA-Z0-9_]/g, "_");
}

function createSplitAlias(relativeSplitName: string): string {
	return `split_${toSafeIdentifier(relativeSplitName)}`;
}

interface SplitImportDescriptor {
	alias: string;
	entryKey: string;
	importPath: string;
}

function buildSplitImportDescriptors(
	entries: GeneratedRegistryEntry[],
	requests: RequestsMap,
): SplitImportDescriptor[] {
	const splitDescriptors: SplitImportDescriptor[] = [];

	for (const entry of entries) {
		const splitFileName = requests[entry.key];
		if (!splitFileName) {
			continue;
		}

		const splitPathInfo = resolveSplitPathInfo(entry, splitFileName);
		splitDescriptors.push({
			alias: createSplitAlias(splitPathInfo.relativeSplitName),
			entryKey: entry.key,
			importPath: splitPathInfo.relativeImportPath,
		});
	}

	return splitDescriptors;
}

function buildCollectionToRequestKeys(
	entries: GeneratedRegistryEntry[],
): string {
	const collectionMap: Record<string, string[]> = {};

	for (const entry of entries) {
		if (!collectionMap[entry.collection]) {
			collectionMap[entry.collection] = [];
		}
		collectionMap[entry.collection].push(entry.key);
	}

	const lines = Object.entries(collectionMap)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(
			([collection, keys]) =>
				`  "${collection}": [${keys
					.sort()
					.map((key) => `"${key}"`)
					.join(", ")}],`,
		)
		.join("\n");

	return `export const collectionToRequestKeys = {\n${lines}\n} as const;`;
}

function buildInlineEntryContent(entry: GeneratedRegistryEntry): string {
	const {
		escapedCollection,
		escapedDataSourceKey,
		escapedKey,
		escapedMethod,
		escapedName,
		escapedUrl,
		payloadDataStr,
	} = serializeEntryFields(entry);

	return `  "${entry.key}": {
    key: "${escapedKey}",
    name: "${escapedName}",
    collection: "${escapedCollection}",
    dataSourceKey: "${escapedDataSourceKey}",
    method: "${escapedMethod}",
    url: "${escapedUrl}",
    payloadSchema: ${entry.payloadSchema},
    payloadData: ${payloadDataStr},
  },`;
}

function buildRegistryContent(
	entries: GeneratedRegistryEntry[],
	requests: RequestsMap,
): string {
	const sortedEntries = [...entries].sort((a, b) => a.key.localeCompare(b.key));
	const splitDescriptors = buildSplitImportDescriptors(sortedEntries, requests);
	const splitAliasByKey = new Map(
		splitDescriptors.map((descriptor) => [
			descriptor.entryKey,
			descriptor.alias,
		]),
	);

	const splitImports = splitDescriptors
		.map(
			(descriptor) =>
				`import { requestEntry as ${descriptor.alias}RequestEntry } from "${descriptor.importPath}";`,
		)
		.join("\n");

	const entryLines = sortedEntries
		.map((entry) => {
			const splitAlias = splitAliasByKey.get(entry.key);
			if (splitAlias) {
				return `  "${entry.key}": ${splitAlias}RequestEntry,`;
			}

			return buildInlineEntryContent(entry);
		})
		.join("\n\n");

	const collectionMapping = buildCollectionToRequestKeys(entries);

	return `/**
 * This file was auto-generated by generate-custom-requests script.
 * Do not edit manually.
 */
import { z } from "zod";
${splitImports ? `${splitImports}\n` : ""}
export const generatedCustomRequestsRegistry = {
 ${entryLines}
} as const;

export const customRequestsRegistry = generatedCustomRequestsRegistry;

export type CustomRequestRegistryKey = keyof typeof customRequestsRegistry;

${collectionMapping}
`;
}

function runBiomeFix(filePath: string, logger: Logger): Promise<void> {
	return new Promise((resolvePromise) => {
		execFile(
			"biome",
			["check", "--write", filePath],
			(error, stdout, stderr) => {
				if (stdout) logger.debug(stdout);
				if (stderr) logger.debug(stderr);
				if (error) {
					logger.info(
						`Biome retornou erro (pode ser apenas warnings): ${error.message}`,
					);
				}
				resolvePromise();
			},
		);
	});
}

export async function writeGeneratedRegistry(
	entries: GeneratedRegistryEntry[],
	outputDir: string,
	requests: RequestsMap = {},
	logger?: Logger,
): Promise<void> {
	const activeLogger = logger ?? defaultRuntimeLogger;
	const content = buildRegistryContent(entries, requests);
	const outputPath = resolve(outputDir, "generated-registry.ts");

	activeLogger.debug("Gerando registry");
	activeLogger.debug(`registry path: ${outputPath}`);
	mkdirSync(resolve(outputDir), { recursive: true });

	writeFileSync(outputPath, content, "utf-8");

	await runBiomeFix(outputPath, activeLogger);
}
