import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Logger } from "@scripts/generators/src/lib/logger";
import { logger as defaultRuntimeLogger } from "@scripts/generators/src/lib/logger";
import {
	escapeString,
	serializePayloadData,
} from "@scripts/generators/src/lib/strings";
import type { GeneratedRegistryEntry } from "../../../@types/generated-registry";
import type { RequestsMap } from "../../../@types/script-config";
import { toDataSourceDir, toSafePathSegment } from "./path-utils";

function buildSplitFileContent(
	entry: GeneratedRegistryEntry,
	displayName: string,
): string {
	const escapedKey = escapeString(entry.key);
	const escapedName = escapeString(displayName);
	const escapedCollection = escapeString(entry.collection);
	const escapedDataSourceKey = escapeString(entry.dataSourceKey);
	const escapedMethod = escapeString(entry.method);
	const escapedUrl = escapeString(entry.url);
	const payloadDataStr = serializePayloadData(entry.payloadData);

	return `import { z } from "zod";

/**
 * Custom request: ${escapedName}
 * Collection: ${entry.collection}
 * Method: ${entry.method}
 * URL: ${entry.url}
 *
 * This file was auto-generated by generate-custom-requests script.
 * Do not edit manually — this file is preserved on regeneration.
 */
export const payloadSchema = ${entry.payloadSchema};

export const payloadData = ${payloadDataStr};

export const requestEntry = {
	key: "${escapedKey}",
	name: "${escapedName}",
	collection: "${escapedCollection}",
	dataSourceKey: "${escapedDataSourceKey}",
	method: "${escapedMethod}",
	url: "${escapedUrl}",
	payloadSchema,
	payloadData,
} as const;
`;
}

export function writeSplitFile(
	entry: GeneratedRegistryEntry,
	splitFileName: string,
	outputDir: string,
	logger?: Logger,
): void {
	const activeLogger = logger ?? defaultRuntimeLogger;
	const dataSourceDir = toDataSourceDir(entry.dataSourceKey);
	const collectionDir = toSafePathSegment(entry.collection);
	const splitCollectionDir = join(outputDir, dataSourceDir, collectionDir);
	const filePath = join(splitCollectionDir, `${splitFileName}.ts`);

	mkdirSync(splitCollectionDir, { recursive: true });

	const content = buildSplitFileContent(entry, splitFileName);
	writeFileSync(filePath, content, "utf-8");
	activeLogger.debug(`Split file atualizado: ${splitFileName}`);

	const legacyKeyFilePath = join(outputDir, `${entry.key}.ts`);
	if (
		splitFileName !== entry.key &&
		existsSync(legacyKeyFilePath) &&
		legacyKeyFilePath !== filePath
	) {
		unlinkSync(legacyKeyFilePath);
		activeLogger.debug(`Split file legado removido: ${entry.key}.ts`);
	}

	const legacyNamedFilePath = join(outputDir, `${splitFileName}.ts`);
	if (existsSync(legacyNamedFilePath) && legacyNamedFilePath !== filePath) {
		unlinkSync(legacyNamedFilePath);
		activeLogger.debug(`Split file legado removido: ${splitFileName}.ts`);
	}

	const legacyCollectionPath = join(
		outputDir,
		collectionDir,
		`${splitFileName}.ts`,
	);
	if (existsSync(legacyCollectionPath) && legacyCollectionPath !== filePath) {
		unlinkSync(legacyCollectionPath);
		activeLogger.debug(
			`Split file legado removido (sem dataSourceKey): ${collectionDir}/${splitFileName}.ts`,
		);
	}
}

export function writeAllSplitFiles(
	entries: GeneratedRegistryEntry[],
	requests: RequestsMap,
	outputDir: string,
	logger?: Logger,
): void {
	const activeLogger = logger ?? defaultRuntimeLogger;
	const splitRequestKeys = new Set(Object.keys(requests));
	const splitEntries = entries.filter((entry) =>
		splitRequestKeys.has(entry.key),
	);

	for (const entry of splitEntries) {
		const splitFileName = requests[entry.key];
		writeSplitFile(entry, splitFileName, outputDir, activeLogger);
	}

	activeLogger.info(`${splitEntries.length} split files atualizados`);
}
