#!/usr/bin/env sh

while read -r local_ref local_sha remote_ref remote_sha; do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    printf '\n';
    printf '\033[1;31m✖ Push para a branch main está bloqueado\033[0m\n'
    printf '\033[1;33m↳ Faça push para staging.\033[0m\n'
    printf '\n';
    exit 1
  fi
done

echo "pre-push checks..."

pnpm knip:silent
pnpm biome check
pnpm test

pnpm build
pnpm typecheck
